# Practicing the Prop lookups
By Divya Mistry

Part of the Python for Data Journalism introductory course taught by Ben Welsh.

In [2]:
import pandas as pd

In [3]:
props = pd.read_csv("http://www.firstpythonnotebook.org/_static/committees.csv")

In [4]:
props.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
0,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,382,1374469,YES ON PROPOSITION 51 - CALIFORNIANS FOR QUALI...,SUPPORT
1,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,383,1220380,COMMUNITY COLLEGE FACILITY COALITION ISSUES CO...,SUPPORT
2,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,384,1282321,TORLAKSON'S INVEST IN CALIFORNIA A BALLOT MEAS...,SUPPORT
3,ocd-contest/b51dc64d-3562-4913-a190-69f5088c22a6,1376258,70,PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...,385,1382843,CALIFORNIA TAXPAYERS AND EDUCATORS OPPOSED TO ...,OPPOSE
4,ocd-contest/85990193-9d6f-4600-b8e7-bf1317841d82,1362198,71,PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...,386,1362973,YES ON PROPOSITION 52 - A COALITION OF CALIFOR...,SUPPORT

In [5]:
props.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 102 entries, 0 to 101
Data columns (total 8 columns):
ocd_prop_id               102 non-null object
calaccess_prop_id         102 non-null int64
ccdc_prop_id              102 non-null int64
prop_name                 102 non-null object
ccdc_committee_id         102 non-null int64
calaccess_committee_id    102 non-null int64
committee_name            102 non-null object
committee_position        102 non-null object
dtypes: int64(4), object(4)
memory usage: 6.4+ KB

In [6]:
props.prop_name.head()

0    PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
1    PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
2    PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
3    PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...
4    PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...
Name: prop_name, dtype: object

In [7]:
props.prop_name.value_counts()

PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE CRIMINAL PROCEEDINGS AND SENTENCING. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                           13
PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTHCARE, TOBACCO USE PREVENTION, RESEARCH, AND LAW ENFORCEMENT. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.    12
PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.                                                                                                   11
PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.                                                                                                 9
PROPOSITION 055 - TAX EXTENSION TO FUND EDUCATION AND HEALTHCARE. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                          8
PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON SINGLE-USE PLASTIC BAGS.                                                                                         7
PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.                                                                                                             7
PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES OF 2016), ALLEN. CAMPAIGN FINANCE: VOTER INSTRUCTION                                                              6
PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOTER APPROVAL. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                                 4
PROPOSITION 054 - LEGISLATURE. LEGISLATION AND PROCEEDINGS. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                                                    4
PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUTES OF 2014), LARA. ENGLISH LANGUAGE EDUCATION                                                                     4
PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.                                                                                                 4
PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-12 SCHOOL AND COMMUNITY COLLEGE FACILITIES. INITIATIVE STATUTORY AMENDMENT.                                       4
PROPOSITION 052 - STATE FEES ON HOSPITALS. FEDERAL MEDI-CAL MATCHING FUNDS. INITIATIVE STATUTORY AND CONSTITUTIONAL AMENDMENT.                                  3
PROPOSITION 061- STATE PRESCRIPTION DRUG PURCHASES. PRICING STANDARDS. INITIATIVE STATUTE.                                                                      3
PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH REQUIREMENTS. INITIATIVE STATUTE.                                                                                 2
PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INITIATIVE STATUTE.                                                                                                   1
Name: prop_name, dtype: int64

In [8]:
props.prop_name.value_counts().reset_index()

                                                index  prop_name
0   PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE...         13
1   PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTH...         12
2   PROPOSITION 064- MARIJUANA LEGALIZATION. INITI...         11
3   PROPOSITION 066- DEATH PENALTY. PROCEDURES. IN...          9
4   PROPOSITION 055 - TAX EXTENSION TO FUND EDUCAT...          8
5   PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON...          7
6   PROPOSITION 062- DEATH PENALTY. INITIATIVE STA...          7
7   PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES ...          6
8   PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOT...          4
9   PROPOSITION 054 - LEGISLATURE. LEGISLATION AND...          4
10  PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUT...          4
11  PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...          4
12  PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-...          4
13  PROPOSITION 052 - STATE FEES ON HOSPITALS. FED...          3
14  PROPOSITION 061- STATE PRESCRIPTION DRUG PURCH...          3
15  PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH ...          2
16  PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INIT...          1

In [9]:
contribs = pd.read_csv("http://www.firstpythonnotebook.org/_static/contributions.csv")

In [10]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [11]:
contribs.contributor_city.value_counts().reset_index()

                      index  contributor_city
0           WEST SACRAMENTO             28671
1             SAN FRANCISCO              1729
2               LOS ANGELES              1501
3                 SAN DIEGO              1104
4                SACRAMENTO               974
5                  SAN JOSE               700
6                  BERKELEY               624
7                   OAKLAND               613
8                 PALO ALTO               580
9             SANTA BARBARA               473
10               SANTA CRUZ               381
11               MENLO PARK               290
12                LOS GATOS               245
13             SANTA MONICA               240
14              BAKERSFIELD               224
15               SAN RAFAEL               216
16              MILL VALLEY               213
17                SUNNYVALE               201
18             WALNUT CREEK               200
19               LONG BEACH               199
20                 NEW YORK               199
21                    DAVIS               193
22                 PASADENA               184
23               SANTA ROSA               182
24                   IRVINE               164
25             REDWOOD CITY               164
26                SAN MATEO               159
27                ENCINITAS               158
28                  CONCORD               147
29            MOUNTAIN VIEW               135
...                     ...               ...
1237             OCCIDENTAL                 1
1238               SANTA FE                 1
1239                BONSALL                 1
1240             MORRISTOWN                 1
1241           GAITHERSBURG                 1
1242               RATHDRUM                 1
1243                 BROOKS                 1
1244             CHESTERTON                 1
1245               DUNNIGAN                 1
1246           FOREST HILLS                 1
1247               NORCROSS                 1
1248             PORTSMOUTH                 1
1249            LITTLESTOWN                 1
1250              SOMES BAR                 1
1251        ROWLAND HEIGHTS                 1
1252             BETTENDORF                 1
1253              BROOKLINE                 1
1254           MOUNTAIN VEW                 1
1255            CASA GRANDE                 1
1256               LEESBURG                 1
1257                DULZURA                 1
1258               BIG PINE                 1
1259        WHITE BEAR LAKE                 1
1260           SEVERNA PARK                 1
1261             IJAMSVILLE                 1
1262           COLLIERVILLE                 1
1263           SNATA MONICA                 1
1264  ROLLING HILLS ESTATES                 1
1265           LAKE STEVENS                 1
1266                KLAMATH                 1

[1267 rows x 2 columns]

In [12]:
contribs.contributor_state.value_counts().reset_index()

   index  contributor_state
0     CA              53837
1     NY                364
2     TX                143
3     NJ                134
4     WA                131
5     VA                115
6     GA                115
7     MA                111
8     AZ                110
9     PA                 99
10    FL                 98
11    CO                 85
12    OR                 82
13    IL                 82
14    NC                 73
15    DC                 61
16    VT                 57
17    DE                 45
18    OH                 44
19    MI                 41
20    NV                 39
21    MD                 38
22    MO                 37
23    CT                 35
24    MN                 34
25    KS                 30
26    NM                 29
27    SC                 27
28    HI                 25
29    WI                 21
30    TN                 19
31    LA                 19
32    ME                 18
33    UT                 18
34    BC                 16
35    NE                 15
36    AK                 14
37    RI                 13
38    WY                 13
39    KY                 12
40    IN                 11
41    OK                 10
42    IA                  9
43    WV                  7
44    NH                  6
45    AL                  4
46    ID                  4
47    MT                  4
48    AB                  3
49    NB                  2
50    TE                  1
51    ON                  1
52     A                  1
53    SD                  1

In [13]:
contribs.contributor_is_self_employed.value_counts()

False    55589
True       790
Name: contributor_is_self_employed, dtype: int64

In [14]:
contribs.amount.between(5,500)

0         True
1         True
2         True
3        False
4         True
5         True
6         True
7         True
8         True
9         True
10        True
11        True
12        True
13       False
14       False
15        True
16        True
17        True
18        True
19        True
20       False
21       False
22        True
23        True
24       False
25        True
26       False
27       False
28       False
29       False
         ...
56349     True
56350     True
56351     True
56352     True
56353     True
56354     True
56355     True
56356     True
56357     True
56358     True
56359     True
56360     True
56361     True
56362     True
56363     True
56364     True
56365    False
56366    False
56367    False
56368    False
56369    False
56370    False
56371    False
56372    False
56373    False
56374    False
56375    False
56376    False
56377    False
56378    False
Name: amount, Length: 56379, dtype: bool

In [15]:
contribs.amount.max()

12500000.0

In [16]:
contribs.amount.min()

-150000.0

In [17]:
contribs.amount.between(5000,10000).value_counts().reset_index()

   index  amount
0  False   55801
1   True     578

In [18]:
contribs.loc[contribs.contributor_is_self_employed == True].amount.describe()

count      790.000000
mean       215.523810
std       2369.271402
min         10.000000
25%         75.000000
50%        100.000000
75%        120.000000
max      65000.000000
Name: amount, dtype: float64

In [19]:
contribs.loc[contribs.contributor_is_self_employed == False].amount.describe()

count    5.558900e+04
mean     7.354164e+03
std      1.599721e+05
min     -1.500000e+05
25%      1.000000e+02
50%      2.870800e+02
75%      2.870800e+02
max      1.250000e+07
Name: amount, dtype: float64

In [20]:
contribs.head()

,calaccess_committee_id,committee_name,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,BERGMAN,GRETCHEN,SPRING VALLEY,CA,91978,A NEW PATH,EXECUTIVE DIRECTOR,False,84.0
1,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-09-18,KAHLE,MYRNA,SAN DIEGO,CA,92109,NATIONAL SCHOOL DISTRICT,TEACHER,False,35.0
2,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-15,MCDEVITT,LEO,ESCONDIDO,CA,92025,LIFE IONIZERS,SEO/CONTENT MANAGER,False,198.0
3,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-08-10,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,False,-50.0
4,1386560,ADULT USE CAMPAIGN FOR PROPOSITION 64; THE,2083796,2016-07-26,WARREN-SAMARIPA,STEPHANIE,SAN DIEGO,CA,92116,STEPHANIE WARREN SAMARIPA,ENTREPRENEUR,True,50.0

In [21]:
contribs.contributor_occupation.value_counts()

CORRECTIONAL OFFICER             28617
RETIRED                           3795
UNEMPLOYED                        2630
NOT EMPLOYED                      2500
ATTORNEY                          1364
ENGINEER                           537
PROFESSOR                          393
PHYSICIAN                          356
TEACHER                            352
OWNER                              305
WRITER                             275
CONSULTANT                         251
SALES                              197
MANAGER                            191
SOFTWARE ENGINEER                  172
DIRECTOR                           164
PRESIDENT                          160
CHIEF EXECUTIVE OFFICER            122
PSYCHOLOGIST                       113
HOMEMAKER                          108
SCIENTIST                          105
CONTRACTOR                         102
ARTIST                              97
REGISTERED NURSE                    93
EXECUTIVE                           92
NOT-EMPLOYED                        87
REAL ESTATE                         86
ARCHITECT                           86
DESIGNER                            82
MARKETING                           81
                                 ...
TIMBER FARMER                        1
ACTRESS/SCREENWRITER/PRODUCER        1
MEDICAL ADMINISTRATIVE               1
AUTO DETAILER                        1
VICE PRESIDENT OF REVENUE            1
VENTURE CAPITAL INVESTOR             1
BARISTA                              1
DJ                                   1
ECOMMERCE                            1
SOLAR                                1
MEDICAL CODING                       1
POSTDOCTORAL FELLOW                  1
COMPUTER PROGRAMER                   1
PROFESSOR OF LAW                     1
WATER TESTING                        1
HVAC                                 1
COPY EDITOR                          1
DOCUMENTARY FILMMAKER                1
INSURANCE SALES                      1
BAR OWNER                            1
ADMINISTRATIVE DIRECTOR              1
PERFORMER                            1
PRIVATE EQUITY                       1
PAYROLL                              1
INFRASTRUCTURE ENGINEERING           1
BUSINESS AFFAIRS EXECUTIVE           1
PHYSICIAN RADIOLOGIST                1
KNOWLEDGE MANAGER                    1
FIREARMS INSTRUCTOR                  1
TEACHER (RETIRED)                    1
Name: contributor_occupation, Length: 2196, dtype: int64

In [22]:
contribs.shape

(56379, 13)

In [23]:
9012.0 / (56379 - 28617)

0.3246163821050357

In [24]:
(9012.0 - 3795) / (56379 - 28617)

0.18791873784309487

In [27]:
props.prop_name.value_counts()

PROPOSITION 057 - CRIMINAL SENTENCES. JUVENILE CRIMINAL PROCEEDINGS AND SENTENCING. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                           13
PROPOSITION 056 - CIGARETTE TAX TO FUND HEALTHCARE, TOBACCO USE PREVENTION, RESEARCH, AND LAW ENFORCEMENT. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.    12
PROPOSITION 064- MARIJUANA LEGALIZATION. INITIATIVE STATUTE.                                                                                                   11
PROPOSITION 066- DEATH PENALTY. PROCEDURES. INITIATIVE STATUTE.                                                                                                 9
PROPOSITION 055 - TAX EXTENSION TO FUND EDUCATION AND HEALTHCARE. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                          8
PROPOSITION 067- REFERENDUM TO OVERTURN BAN ON SINGLE-USE PLASTIC BAGS.                                                                                         7
PROPOSITION 062- DEATH PENALTY. INITIATIVE STATUTE.                                                                                                             7
PROPOSITION 059- SB 254 (CHAPTER 20, STATUTES OF 2016), ALLEN. CAMPAIGN FINANCE: VOTER INSTRUCTION                                                              6
PROPOSITION 053 - REVENUE BONDS. STATEWIDE VOTER APPROVAL. INITIATIVE CONSTITUTIONAL AMENDMENT.                                                                 4
PROPOSITION 054 - LEGISLATURE. LEGISLATION AND PROCEEDINGS. INITIATIVE CONSTITUTIONAL AMENDMENT AND STATUTE.                                                    4
PROPOSITION 058 - SB 1174 (CHAPTER 753, STATUTES OF 2014), LARA. ENGLISH LANGUAGE EDUCATION                                                                     4
PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE.                                                                                                 4
PROPOSITION 051 - SCHOOL BONDS. FUNDING FOR K-12 SCHOOL AND COMMUNITY COLLEGE FACILITIES. INITIATIVE STATUTORY AMENDMENT.                                       4
PROPOSITION 052 - STATE FEES ON HOSPITALS. FEDERAL MEDI-CAL MATCHING FUNDS. INITIATIVE STATUTORY AND CONSTITUTIONAL AMENDMENT.                                  3
PROPOSITION 061- STATE PRESCRIPTION DRUG PURCHASES. PRICING STANDARDS. INITIATIVE STATUTE.                                                                      3
PROPOSITION 060- ADULT FILMS. CONDOMS. HEALTH REQUIREMENTS. INITIATIVE STATUTE.                                                                                 2
PROPOSITION 065- CARRY-OUT BAGS. CHARGES. INITIATIVE STATUTE.                                                                                                   1
Name: prop_name, dtype: int64

In [59]:
prop64name = "PROPOSITION 063- FIREARMS. AMMUNITION SALES. INTIATIVE STATUTE."

In [60]:
prop64data = props[props.prop_name == prop64name]

In [61]:
prop64data.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name,committee_position
70,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE
71,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,453,1380746,"STOP PROP 63, A GRASSROOTS, COMMON-SENSE EFFOR...",OPPOSE
72,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT
73,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,455,1387279,"VETO GUNMAGEDDON, CITIZENS WHO ARE OPPOSED TO ...",OPPOSE

In [62]:
prop64data.describe()

,calaccess_prop_id,ccdc_prop_id,ccdc_committee_id,calaccess_committee_id
count,4.0,4.0,4.000000,4.000000e+00
mean,1381803.0,82.0,453.500000,1.382692e+06
std,0.0,0.0,1.290994,3.124441e+03
min,1381803.0,82.0,452.000000,1.380675e+06
25%,1381803.0,82.0,452.750000,1.380728e+06
50%,1381803.0,82.0,453.500000,1.381406e+06
75%,1381803.0,82.0,454.250000,1.383370e+06
max,1381803.0,82.0,455.000000,1.387279e+06

In [63]:
prop64data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4 entries, 70 to 73
Data columns (total 8 columns):
ocd_prop_id               4 non-null object
calaccess_prop_id         4 non-null int64
ccdc_prop_id              4 non-null int64
prop_name                 4 non-null object
ccdc_committee_id         4 non-null int64
calaccess_committee_id    4 non-null int64
committee_name            4 non-null object
committee_position        4 non-null object
dtypes: int64(4), object(4)
memory usage: 288.0+ bytes

In [64]:
contribs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 56379 entries, 0 to 56378
Data columns (total 13 columns):
calaccess_committee_id          56379 non-null int64
committee_name                  56379 non-null object
calaccess_filing_id             56379 non-null int64
date_received                   56379 non-null object
contributor_lastname            56375 non-null object
contributor_firstname           53411 non-null object
contributor_city                56369 non-null object
contributor_state               56363 non-null object
contributor_zip                 56366 non-null object
contributor_employer            48572 non-null object
contributor_occupation          53273 non-null object
contributor_is_self_employed    56379 non-null bool
amount                          56379 non-null float64
dtypes: bool(1), float64(1), int64(2), object(9)
memory usage: 5.2+ MB

In [65]:
prop64_with_contribs = pd.merge(prop64data, contribs, on="calaccess_committee_id")

In [66]:
prop64_with_contribs.head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
0,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-01-13,CALIFORNIA RIFLE & PISTOL ASSOCIATION,NaN,FULLERTON,CA,92835,NaN,NaN,False,10000.0
1,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-01-27,BORDIN,CRAIG,SANTA ROSA,CA,95404,NaN,RETIRED,False,100.0
2,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-01-27,FRYER,WILTON,SMARTVILLE,CA,95977,NaN,RETIRED,False,100.0
3,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-01-27,GREEN,MELVIN E.,QUINCY,CA,95971,NaN,RETIRED,False,100.0
4,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-01-27,"GUN OWNERS OF CALIFORNIA, INC.",NaN,SACRAMENTO,CA,95833,NaN,NaN,False,10000.0

In [67]:
prop64_with_contribs.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 11025 entries, 0 to 11024
Data columns (total 20 columns):
ocd_prop_id                     11025 non-null object
calaccess_prop_id               11025 non-null int64
ccdc_prop_id                    11025 non-null int64
prop_name                       11025 non-null object
ccdc_committee_id               11025 non-null int64
calaccess_committee_id          11025 non-null int64
committee_name_x                11025 non-null object
committee_position              11025 non-null object
committee_name_y                11025 non-null object
calaccess_filing_id             11025 non-null int64
date_received                   11025 non-null object
contributor_lastname            11025 non-null object
contributor_firstname           10913 non-null object
contributor_city                11023 non-null object
contributor_state               11020 non-null object
contributor_zip                 11023 non-null object
contributor_employer            6836 non-null object
contributor_occupation          10912 non-null object
contributor_is_self_employed    11025 non-null bool
amount                          11025 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 1.7+ MB

In [68]:
prop64_with_contribs.amount.sum()

3491136.6800000002

In [69]:
prop64_with_contribs.committee_position.value_counts()

OPPOSE     5568
SUPPORT    5457
Name: committee_position, dtype: int64

In [70]:
support = prop64_with_contribs[prop64_with_contribs.committee_position == "SUPPORT"]
oppose = prop64_with_contribs[prop64_with_contribs.committee_position == 'OPPOSE']

In [71]:
support.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5457 entries, 5293 to 10749
Data columns (total 20 columns):
ocd_prop_id                     5457 non-null object
calaccess_prop_id               5457 non-null int64
ccdc_prop_id                    5457 non-null int64
prop_name                       5457 non-null object
ccdc_committee_id               5457 non-null int64
calaccess_committee_id          5457 non-null int64
committee_name_x                5457 non-null object
committee_position              5457 non-null object
committee_name_y                5457 non-null object
calaccess_filing_id             5457 non-null int64
date_received                   5457 non-null object
contributor_lastname            5457 non-null object
contributor_firstname           5450 non-null object
contributor_city                5457 non-null object
contributor_state               5454 non-null object
contributor_zip                 5457 non-null object
contributor_employer            3298 non-null object
contributor_occupation          5450 non-null object
contributor_is_self_employed    5457 non-null bool
amount                          5457 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 858.0+ KB

In [72]:
oppose.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 5568 entries, 0 to 11024
Data columns (total 20 columns):
ocd_prop_id                     5568 non-null object
calaccess_prop_id               5568 non-null int64
ccdc_prop_id                    5568 non-null int64
prop_name                       5568 non-null object
ccdc_committee_id               5568 non-null int64
calaccess_committee_id          5568 non-null int64
committee_name_x                5568 non-null object
committee_position              5568 non-null object
committee_name_y                5568 non-null object
calaccess_filing_id             5568 non-null int64
date_received                   5568 non-null object
contributor_lastname            5568 non-null object
contributor_firstname           5463 non-null object
contributor_city                5566 non-null object
contributor_state               5566 non-null object
contributor_zip                 5566 non-null object
contributor_employer            3538 non-null object
contributor_occupation          5462 non-null object
contributor_is_self_employed    5568 non-null bool
amount                          5568 non-null float64
dtypes: bool(1), float64(1), int64(5), object(13)
memory usage: 875.4+ KB

In [73]:
support.amount.sum()

2829869.1000000001

In [74]:
oppose.amount.sum()

661267.58000000007

In [75]:
support.amount.sum() / prop64_with_contribs.amount.sum()

0.81058673990386421

In [76]:
oppose.amount.sum() / prop64_with_contribs.amount.sum()

0.18941326009613579

In [77]:
merged = prop64_with_contribs

In [78]:
merged.sort_values(by="amount", ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
7534,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2083720,2016-07-01,PARKER,SEAN,PALO ALTO,CA,94301,SEAN PARKER FOUNDATION,CHAIRMAN,False,400000.0
5729,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-03-14,MARCUS,GEORGE M.,PALO ALTO,CA,94304,MARCUS & MILICHAP COMPANY,CHAIRMAN,False,250000.0
5529,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-02-22,BUELL,SUSIE TOMPKINS,SAN FRANCISCO,CA,94129,NaN,NOT EMPLOYED,False,200000.0
5812,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-01-28,PRITZKER,NICHOLAS,SAN FRANCISCO,CA,94129,TAO CAPITAL PARTNERS,DIRECTOR OF STRATEGIC PLANNING,False,150000.0
5813,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-03-03,PRITZKER,NICHOLAS,SAN FRANCISCO,CA,94129,TAO CAPITAL PARTNERS,DIRECTOR OF STRATEGIC PLANNING,False,100000.0

In [79]:
support.sort_values(by="amount", ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
7534,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2083720,2016-07-01,PARKER,SEAN,PALO ALTO,CA,94301,SEAN PARKER FOUNDATION,CHAIRMAN,False,400000.0
5729,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-03-14,MARCUS,GEORGE M.,PALO ALTO,CA,94304,MARCUS & MILICHAP COMPANY,CHAIRMAN,False,250000.0
5529,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-02-22,BUELL,SUSIE TOMPKINS,SAN FRANCISCO,CA,94129,NaN,NOT EMPLOYED,False,200000.0
5812,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2038645,2016-01-28,PRITZKER,NICHOLAS,SAN FRANCISCO,CA,94129,TAO CAPITAL PARTNERS,DIRECTOR OF STRATEGIC PLANNING,False,150000.0
5293,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,454,1380675,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,SUPPORT,NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...,2013128,2015-12-30,"11 WEST PARTNERS, LLC",NaN,SAN FRANCISCO,CA,94115,NaN,NaN,False,100000.0

In [80]:
oppose.sort_values(by="amount", ascending=False).head()

,ocd_prop_id,calaccess_prop_id,ccdc_prop_id,prop_name,ccdc_committee_id,calaccess_committee_id,committee_name_x,committee_position,committee_name_y,calaccess_filing_id,date_received,contributor_lastname,contributor_firstname,contributor_city,contributor_state,contributor_zip,contributor_employer,contributor_occupation,contributor_is_self_employed,amount
1594,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2097584,2016-10-04,NATIONAL RIFLE ASSOCIATION POLITICAL VICTORY FUND,NaN,FAIRFAX,VA,22030,NaN,NaN,False,50000.0
16,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-02-25,NATIONAL RIFLE ASSOCIATION OF AMERICA,NaN,FAIRFAX,VA,22030,NaN,NaN,False,45000.0
5,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2038369,2016-02-02,CALIFORNIA RIFLE & PISTOL ASSOCIATION,NaN,FULLERTON,CA,92835,NaN,NaN,False,35000.0
620,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2082835,2016-08-19,CALIFORNIA WATERFOWL ASSOCIATION,NaN,ROSEVILLE,CA,95678,NaN,NaN,False,25000.0
2026,ocd-contest/e02dc48a-2ed3-4a87-859b-26c90f0539e7,1381803,82,PROPOSITION 063- FIREARMS. AMMUNITION SALES. I...,452,1382067,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",OPPOSE,"COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...",2097584,2016-10-19,"GUN OWNERS OF CALIFORNIA, INC.",NaN,SACRAMENTO,CA,95833,NaN,NaN,False,15000.0

In [81]:
merged.groupby("committee_name_x").amount.sum().reset_index().sort_values(by="amount", ascending=False)

                                    committee_name_x      amount
1  NEWSOM BALLOT MEASURE COMMITTEE; SAFETY FOR AL...  2829869.10
0  COALITION FOR CIVIL LIBERTIES - NO ON 63, A PR...   430845.42
2  STOP PROP 63, A GRASSROOTS, COMMON-SENSE EFFOR...   178112.56
3  VETO GUNMAGEDDON, CITIZENS WHO ARE OPPOSED TO ...    52309.60

In [82]:
merged.groupby(['contributor_firstname', 'contributor_lastname']).amount.sum().reset_index().sort_values(by="amount", ascending=False)

     contributor_firstname contributor_lastname    amount
4147                  SEAN               PARKER  400000.0
1540             GEORGE M.               MARCUS  250000.0
3422              NICHOLAS             PRITZKER  250000.0
4379        SUSIE TOMPKINS                BUELL  210000.0
1089                 DIANE               WILSEY  110000.0
72               ALEXANDER                SOROS  100000.0
1296             ELIZABETH               SIMONS  100000.0
791                 DAGMAR                DOLBY  100000.0
2912               MARC R.              BENIOFF   50000.0
1620                  GREG                WENDT   50000.0
4091                  SARA             WILLIAMS   50000.0
1390                  EVAN             WILLIAMS   50000.0
4004             RONALD C.               CONWAY   50000.0
165                  ANITA             DONOFRIO   40500.0
2358                 JOYCE              NEWSTAT   25000.0
3841                ROBERT               BRODER   25000.0
3590                   PEG               YORKIN   16825.0
3834                ROBERT             ANDERSON   15000.0
1658               GWYNNED              VITELLO   15000.0
1700          HELEN HILTON               RAISER   11200.0
2518                   KAY              KIMPTON   11000.0
1748            IRWIN MARK               JACOBS   10000.0
4322                STEVEN              LEVITAN   10000.0
31                  AILEEN                GETTY   10000.0
100                 AMANDA                 PEET    7500.0
864                  DAVID              BENIOFF    7500.0
3173               MICHAEL              BORLAND    7000.0
2599                 KEVIN               HUVANE    6000.0
42                    ALAN             BLACKMAN    5250.0
3431                NICOLA                MINER    5000.0
...                    ...                  ...       ...
1096               DIMITRI               KELLER      20.0
3146                 MEGAN              GERSHON      15.0
3228               MICHAEL                MELLO      15.0
2426                 KAREN               CARTER      10.0
1171               DOUGLAS             BROADDUS      10.0
322                BERNARD               GARCIA      10.0
2965                MARINA               FAELLI      10.0
2782                LESLIE              SHANNON      10.0
3539            PATRICK J.                 CRUZ      10.0
1424                 FRANK               JANESH      10.0
3184               MICHAEL            CUCKOVICH      10.0
3148                   MEL         RYAN-ROBERTS      10.0
4625                    VU               BARNES      10.0
4233               STEFANO           FILIPPELLI      10.0
1610                  GREG            BERKOWITZ      10.0
199                ANTHONY             APICHINO      10.0
3661                RACHEL             BROADWIN      10.0
747               COURNTEY      SIPERSTEIN-COOK       9.0
3044                MARNIE              WALTERS       5.0
704                 CLAIRE               AUGUST       5.0
2477                KATHIE                 KAWA       0.0
1202                DWIGHT               BETTEN       0.0
3874                ROBERT                 HILL       0.0
4409              TERRENCE            GRYWINSKI       0.0
321              BERNADINE                HOEFT       0.0
4749               WILLIAM               WEAVER       0.0
406                  BRIAN                MOORE       0.0
358                 BONNIE             WILLDORF       0.0
3745                  RICH                BYRUM       0.0
1656                  GWEN                 HALL       0.0

[4783 rows x 3 columns]

In [84]:
merged.groupby(['contributor_firstname', 'contributor_lastname', 'committee_position']).amount.sum().reset_index().sort_values(by="amount", ascending=False).head(10)

     contributor_firstname contributor_lastname committee_position    amount
4153                  SEAN               PARKER            SUPPORT  400000.0
3427              NICHOLAS             PRITZKER            SUPPORT  250000.0
1543             GEORGE M.               MARCUS            SUPPORT  250000.0
4385        SUSIE TOMPKINS                BUELL            SUPPORT  210000.0
1092                 DIANE               WILSEY            SUPPORT  110000.0
793                 DAGMAR                DOLBY            SUPPORT  100000.0
72               ALEXANDER                SOROS            SUPPORT  100000.0
1299             ELIZABETH               SIMONS            SUPPORT  100000.0
1623                  GREG                WENDT            SUPPORT   50000.0
2917               MARC R.              BENIOFF            SUPPORT   50000.0